### ISSUE TITLE
de-swift hbird memcache keys

### ISSUE THREAD

**Issue by dpgoetz** [troubling/hummingbird#110]
don't use same keys as swift for memcache. just prefix em with hbird or something

**Comment by redbo** [comment]
It might be good to change away from md5 for hash keys if we're breaking from swift anyway.  There are things that are faster and more secure, depending on what we think is important.

**Comment by dpgoetz** [comment]
do we need to worry about a cache flush when doing an upgrade?

**Comment by gholt** [comment]
Probably just need to warn about the cache pressure when doing an upgrade. As in, don't upgrade all your proxies at exactly the same time. If you only have one or two proxies, you probably won't care.

**Comment by gholt** [comment]
I don't think we're going to do this after all because it'd make running Swift+Hummingbird proxies at the same time during upgrades impossible.

**Comment by gholt** [comment]
https://github.com/troubling/hummingbird/pull/244
