### ISSUE TITLE
container server leaks connections

### ISSUE THREAD

**Issue by redbo** [troubling/hummingbird#36]
If I run the func tests in a loop, the container server eventually runs out of file descriptors.  lsof says it's due to open database files.  There must be a race condition or logic problem in my LRU cache or something similar that's causing it to leak.

You really have to Close() every database connection that you open, or it leaks a goroutine and some number of file descriptors for each one.

**Comment by corystone** [comment]
lru cache entries are getting stuck inUse:1 which prevents them from being cleaned out when the cache is full.
