### ISSUE TITLE
use builtin graceful shutdown

### ISSUE THREAD

**Issue by redbo** [troubling/hummingbird#4]
The go http server now has a built-in graceful shutdown: func (*Server) Shutdown.  This is good news, because the BeginShutdown/ConnStateChange stuff in hummingbird/server.go that attempts to implement this is almost certainly beyond saving.

The only thing is I'm not sure about if you still need to call SetKeepAlivesEnabled(false) so connections are closed once they go idle, or if Shutdown() has this functionality built in.

**Comment by nadeemsyed** [comment]
After reading the code it seems like we don't need to call SetKeepAlivesEnabled 
https://github.com/golang/go/blob/release-branch.go1.8/src/net/http/server.go#L2718
Also shutdown won't handle hijacked connection(I guess we only use that for Replication) and also Shutdown will probably wait indefinite for connection to get idle. However I guess we can use pass context in Shutdown to handle timeout.
