### ISSUE TITLE
EOL

### ISSUE THREAD

**Issue by alrs** [troubling/hummingbird#648]
The "no longer under active development" statement in the README is somewhat abrupt. Is this work being taken up somewhere else?

**Comment by creiht** [comment]
Hi Lars,

Thanks for you interest in Hummingbird!  I apologize for this being so abrupt, but our employer has decided to no longer support development of the Hummingbird project.  We are being assigned to other projects, and, unfortunately, there are currently no plans to continue this work.

**Comment by gregorybrzeski** [comment]
@creiht can you share with us what is your employer going to replace hummingbird with ?

**Comment by creiht** [comment]
I apologize that I really can't make any further statements in the matter.
