### ISSUE TITLE
the future of humingbird?

### ISSUE THREAD

**Issue by RocFang** [troubling/hummingbird#649]
Hello, @creiht 
I hope this abrupt message not bother you too much:)
Firstly, Thank you and your team very much for the fantasitic and hard work for swift/hummingbird for these years.

As far as we know, hummingbird project was closed. But according to https://blog.rackspace.com/making-openstack-powered-rackspace-cloud-files-buzz-with-hummingbird, rackspace has been using hummingbird for several years. I'm not sure the close of this project meas whether the depolyed hummingbird clusters in rackspace will migrate to another object storage system(abandon hummingbird totally), or rackspace will continue maintaning a private branch of hummingbird?

Thank

**Comment by creiht** [comment]
Howdy @RocFang,

There is no further work being done internally either, and I do not know what the plan is going forward, and if I did, I probably couldn't talk about it ;) 

Thanks for the kind words.

--
Chuck
